### ISSUE TITLE
请问安装好这个模块之后会导致miui电量曲线显示异常吗

### ISSUE THREAD

**Issue by 923133980** [ayanamist/miui-powerkeeper-hack#2]
是小白，好像安装了这个之后，电池与性能那里看耗电曲线会变得特别平缓？不知道是不是这个模块的原因。还是我乱装了其他东西

**Comment by ayanamist** [comment]
肯定和我这个模块无关

**Comment by 923133980** [comment]
好的，感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月30日(周四) 晚上6:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ayanamist/miui-powerkeeper-hack] 请问安装好这个模块之后会导致miui电量曲线显示异常吗 (#2)




 
肯定和我这个模块无关
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
